services:
  openclaw:
    image: ghcr.io/podmania/openclaw:latest
    userns_mode: "keep-id"
    container_name: openclaw
    ports:
      - 18789:18789
    volumes:
      - ./config:/config
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
